
# listen ports
port: 1088
socks-port: 1080
mixed-port: 1081
# redir-port: 1082
# tproxy-port: 1083

ipv6: false
allow-lan: true
bind-address: "*"

# logger
# log-level: debug
log-level: warning

profile:
  tracing: true
  store-fake-ip: true
  store-selected: true

# dashboard
secret: "clash@lsong.org"
external-ui: ./yacd
external-controller: 0.0.0.0:7880

# authentication of local SOCKS5/HTTP(S) server
authentication:
  - "user:proxy@lsong.org"

experimental:
  sniff-tls-sni: true

tun:
  enable: false
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
# interface-name: br0
auto-route: true # auto set global route
auto-detect-interface: true # conflict with interface-name
# routing-mark: 7777
# ebpf:
#   redirect-to-tun:
#     - eth0

dns:
  enable: true
  ipv6: true
  listen: :1053
  use-hosts: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
#   - tls://1.12.12.12
#   - tls://223.5.5.5:853
#   - tls://dns.rubyfish.cn:853
#   - https://doh.pub/dns-query
#   - https://dns.alidns.com/dns-query
#   - https://119.29.29.29/dns-query
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.direct"
    - "unifi"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.twitter.com'
  fallback:
    - 8.8.8.8
    - 208.67.222.222
    - tls://8.8.4.4:853
#   - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
#   - https://public.dns.iij.jp/dns-query

# Lookup domains via specific nameservers
nameserver-policy:
  'lsong.me': '114.114.114.114'
  'lsong.one': '114.114.114.114'
  'lsong.org': '114.114.114.114'
  'dtting.me': '114.114.114.114'
  'baidu.com': '114.114.114.114'
#  'github.com': '114.114.114.114'
#  'api.github.com': '114.114.114.114'
  'api.cloudflare.com': '114.114.114.114'

# Rule / Global/ Direct (default is Rule)
mode: Rule

proxy-providers:
  v2rayse:
    type: http
    path: proxies/v2rayse.yaml
    url: "https://cdn.jsdelivr.net/gh/song940/freefq@master/proxies/v2rayse.yaml"
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  freefq:
    type: http
    path: proxies/freefq.yaml
    url: "https://cdn.jsdelivr.net/gh/song940/freefq@master/proxies/freefq.yaml"
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: "freefq-auto"
    type: url-test
    use:
      - freefq
    url: "http://www.gstatic.com/generate_204"
    interval: 120

  - name: "v2rayse-auto"
    type: select
    use:
      - v2rayse

  - name: PROXY
    type: select
    proxies:
      - freefq-auto
      - v2rayse-auto

rule-providers:
  reject:
    type: file
    behavior: classical
    path: rules/block.yaml
    interval: 86400

  direct:
    type: file
    behavior: domain
    path: rules/direct.yaml
    interval: 86400

  private:
    type: file
    behavior: domain
    path: rules/private.yaml
    interval: 86400

  apple:
    type: file
    behavior: classical
    path: rules/apple.yaml
    interval: 86400

  google:
    type: file
    behavior: classical
    path: rules/google.yaml
    interval: 86400

  microsoft:
    type: file
    behavior: classical
    path: rules/microsoft.yaml
    interval: 86400

  bing:
    type: file
    behavior: classical
    path: rules/bing.yaml
    interval: 86400

  netflix:
    type: file
    behavior: classical
    path: rules/netflix.yaml
    interval: 86400

  telegram:
    type: file
    behavior: classical
    path: rules/telegram.yaml
    interval: 86400

  twitter:
    type: file
    behavior: classical
    path: rules/twitter.yaml
    interval: 86400

  youtube:
    type: file
    behavior: classical
    path: rules/youtube.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: rules/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: rules/greatfire.yaml
    interval: 86400

  proxy:
    type: file
    behavior: classical
    path: rules/proxy.yaml
    interval: 86400

  cn:
    type: file
    behavior: classical
    path: rules/cn.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: rules/cncidr.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: rules/tld-not-cn.yaml
    interval: 86400

  lan:
    type: file
    behavior: ipcidr
    path: rules/lancidr.yaml
    interval: 86400

rules:
  # DNS Query
  - DST-PORT,53,PROXY
  
  # AD
  - RULE-SET,reject,REJECT

  # DIRECT
  - RULE-SET,cn,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,microsoft,DIRECT

  # PROXY
  - RULE-SET,twitter,PROXY
  - RULE-SET,youtube,PROXY
  - RULE-SET,google,PROXY
  - RULE-SET,netflix,PROXY
  - RULE-SET,telegram,PROXY
  - RULE-SET,bing,PROXY
  - RULE-SET,proxy,PROXY

  # LAN
  - RULE-SET,lan,DIRECT
  - RULE-SET,private,DIRECT

  # Finally
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
  # - MATCH,PROXY
  # - MATCH,DIRECT